repo_url: https://github.com/oxfordmmm/gumpy
repo_name: gumpy
site_name: Gumpy Documentation
docs_dir: docs/
site_dir: /

theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking

nav:
  - Home: README.md
  - Code Reference: reference/

extra:
  version:
    provider: jeremy
plugins:
  - include-markdown
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [gumpy]