name: Docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install requests==2.29.0 mkdocs mkdocs-material>=9.1.8 mkdocs-include-markdown-plugin>=4.0.4 mkdocstrings>=0.21.2 mkdocstrings-python>=1.0.0 mkdocs-gen-files>=0.5.0 mkdocs-literate-nav>=0.6.0 mkdocs-section-index>=0.3.5
      - run: pip install .
      - run: mkdocs gh-deploy --force